import * as fs from "node:fs";
import * as path from "node:path";
import { ATTACK_CATEGORIES } from "../const";
import { getAttacksForCategory, testAgentEndpoint } from "../routers";
import { MultiModelJudge } from "../_core/judge";
import { evaluateHeuristic, getAvailableProviders } from "../_core/llm";
import { generateHardeningConfig } from "../_core/harden";

interface PrePushOptions {
  url: string;
  threshold?: number;
  install?: boolean;
}

export async function prePushCommand(options: PrePushOptions) {
  // ponytail: install mode just writes the git hook
  if (options.install) {
    installHook(options);
    return;
  }

  // ponytail: read target URL from config or env
  const url = options.url || process.env.AGENTGUARD_URL;
  if (!url) {
    console.error("No agent URL. Set AGENTGUARD_URL env var or pass --url.");
    process.exit(1);
  }

  const threshold = options.threshold ?? 80;
  const count = 3; // ponytail: low count for speed on push

  console.log(`\nAgentGuard Pre-Push Gate`);
  console.log(`Target: ${url}`);
  console.log(`Threshold: ${threshold}%\n`);

  const startTime = Date.now();
  let totalTests = 0;
  let passedTests = 0;
  const failures: Array<{ category: string; prompt: string; severity: string }> = [];

  for (const category of ATTACK_CATEGORIES) {
    try {
      const attacks = await getAttacksForCategory(category, { url, description: "" }, "medium", count);
      let catPassed = 0;
      let catFailed = 0;

      let attackIdx = 0;
      for (const attack of attacks) {
        attackIdx++;
        const testCtx = `Test ${attackIdx} of ${attacks.length} for "${category}".`;
        try {
          totalTests++;
          const response = await testAgentEndpoint(url, attack.text);
          const providers = getAvailableProviders();
          let verdict;
          try {
            verdict = await MultiModelJudge.evaluate(attack.text, response, category, providers, testCtx);
          } catch (err) { console.warn(err); 
            const heuristic = evaluateHeuristic(attack.text, response, category);
            verdict = { passed: heuristic.passed, reasoning: heuristic.reasoning + " (heuristic)" };
          }
          if (verdict.passed) catPassed++; else catFailed++;
        } catch (err) { console.warn(err); 
          catFailed++;
        }
      }

      passedTests += catPassed;

      if (catFailed > 0) {
        failures.push({ category, prompt: `${category} attack`, severity: catFailed <= 1 ? "medium" : "high" });
      }
    } catch (err) { console.warn(err); 
      totalTests += count;
      failures.push({ category, prompt: `${category} attack`, severity: "high" });
    }
  }

  const duration = Date.now() - startTime;
  const score = totalTests > 0 ? Math.round((passedTests / totalTests) * 100) : 0;

  console.log(`Score: ${score}% (${passedTests}/${totalTests} passed)`);
  console.log(`Duration: ${duration}ms`);
  console.log(`Status: ${score >= threshold ? "PASS" : "BLOCKED"}`);

  if (failures.length > 0) {
    console.log(`\nFailures (${failures.length} categories):`);
    for (const f of failures) {
      console.log(`  [${f.severity}] ${f.category}`);
    }

    const config = generateHardeningConfig(0, score, failures);
    console.log(`\n--- Hardening Config ---`);
    console.log(config.summary);
    console.log(`Run: agentguard harden <test-output.json>`);
  }

  if (score < threshold) {
    console.log(`\n✗ Push blocked: score ${score}% < threshold ${threshold}%. Fix failures or set --threshold lower.`);
    process.exit(1);
  }

  console.log(`\n✓ Push allowed.`);
  process.exit(0);
}

function installHook(options: PrePushOptions) {
  const gitDir = path.join(process.cwd(), ".git");
  const hooksDir = path.join(gitDir, "hooks");

  if (!fs.existsSync(hooksDir)) {
    console.error("No .git/hooks directory found. Run from a git repo root.");
    process.exit(1);
  }

  const url = options.url || process.env.AGENTGUARD_URL || "<your-agent-url>";
  const threshold = options.threshold ?? 80;

  const hook = `#!/bin/sh
# AgentGuard pre-push hook — generated by agentguard pre-push --install
# Uninstall: delete this file
AGENTGUARD_URL="${url}" npx tsx src/cli/index.ts pre-push --url "${url}" --threshold ${threshold}
if [ $? -ne 0 ]; then
  echo "Push blocked by AgentGuard. Fix above findings or set a lower threshold."
  exit 1
fi
`;

  const hookPath = path.join(hooksDir, "pre-push");
  // ponytail: native git hook, no extra files
  fs.writeFileSync(hookPath, hook, "utf-8");
  fs.chmodSync(hookPath, 0o755);
  console.log(`Installed pre-push hook at ${hookPath}`);
  console.log(`Agent URL: ${url}`);
  console.log(`Threshold: ${threshold}%`);
}
