// Generated report for the Lab vertical slice. Every number is read from the
// evidence bundles collected in the run; none are hand-authored. The committed
// results/lab/REPORT.md is the stable human-facing artifact (regeneration drift
// test: lab/report.drift.test.ts).

import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { EXPERIMENT_ID, type SliceSummary } from "./experiments/destructive-command-relay.js";

function num(v: number | null, digits: number): string {
  return v === null ? "—" : v.toFixed(digits);
}

export function renderReport(summary: SliceSummary): string {
  const lines: string[] = [];
  lines.push(`# AgentGuard Lab — ${EXPERIMENT_ID}`);
  lines.push("");
  lines.push(
    "Generated by `npx tsx lab/run.ts`. Every number below is read from the evidence bundles written by that run; none are hand-authored.",
  );
  lines.push("");
  lines.push("## Case outcomes");
  lines.push("");
  lines.push("| result | cases |");
  lines.push("| --- | --- |");
  for (const [result, count] of Object.entries(summary.results).sort()) {
    lines.push(`| ${result} | ${count} |`);
  }
  lines.push(`| **total** | **${summary.cases}** |`);
  lines.push("");
  lines.push("## Dataset-level agreement (individual judge labels)");
  lines.push("");
  lines.push(
    `Numeric kappa is reported only for pairs with at least ${summary.agreement.policy.minPairedCases} valid paired cases (project policy, not a statistical-precision claim). The aggregate is an unweighted mean over reported pairs, never a single "Cohen's kappa for all judges".`,
  );
  lines.push("");
  lines.push("| judge A | judge B | paired cases | observed | expected | kappa | status |");
  lines.push("| --- | --- | --- | --- | --- | --- | --- |");
  for (const p of summary.agreement.pairs) {
    lines.push(
      `| ${p.judgeA} | ${p.judgeB} | ${p.nPaired} | ${num(p.observedAgreement, 3)} | ${num(p.expectedAgreement, 3)} | ${num(p.kappa, 4)} | ${p.status} |`,
    );
  }
  lines.push("");
  lines.push(
    `meanPairwiseKappa: ${num(summary.agreement.meanPairwiseKappa, 4)} (${summary.agreement.includedPairs} pairs included, ${summary.agreement.excludedPairs} excluded)`,
  );
  if (summary.agreement.excludedBrokenEvidenceCases.length > 0) {
    lines.push(
      `Cases excluded for broken evidence: ${summary.agreement.excludedBrokenEvidenceCases.join(", ")}`,
    );
  }
  lines.push("");
  lines.push("## Artifact replay");
  lines.push("");
  lines.push(
    `Re-verified ${summary.replayVerified}/${summary.cases} bundles via ARTIFACT_REPLAY (integrity + canonical-projection re-score). Failures: ${summary.replayFailures.length === 0 ? "none" : summary.replayFailures.join("; ")}.`,
  );
  lines.push("");
  lines.push("## Claim boundary");
  lines.push("");
  lines.push(
    "This slice demonstrates the Lab foundation: corrected verdict semantics, dataset-level agreement, evidence bundles, and artifact replay over the committed M0 destructive-command-relay observations. It measures pipeline validity under the calibrated M0 simulator; it does not measure real-world LLM-agent security efficacy.",
  );
  lines.push("");
  return lines.join("\n");
}

export function writeReport(resultsRoot: string, summary: SliceSummary): string {
  const path = join(resultsRoot, "REPORT.md");
  writeFileSync(path, renderReport(summary));
  return path;
}
